name: CI (Windows)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: win22
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.11"
              otp: "22"
          - pair:
              elixir: "1.17"
              otp: "27"
          - pair:
              elixir: "1.18"
              otp: "27"
          - pair:
              elixir: "1.18"
              otp: "28"

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/checkout@v5

      - run: mix deps.get

      - run: mix deps.compile

      - run: mix compile

      - run: mix test --only os_windows
